// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application Media Types
//
// Command:
// $ goagen
// --design=goa-adder/design
// --out=$(GOPATH)\src\goa-adder
// --version=v1.3.1

package app
